spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
        #show_sql: true
        format_sql: true

logging:
  level:
#    org.hibernate: debug
    org.hibernate.stat: debug
    org.hibernate.SQL: debug
#    org.hibernate.type: trace